# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eyeParserBuilder.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_eyeTrackerSelection(object):
    def setupUi(self, eyeTrackerSelection):
        eyeTrackerSelection.setObjectName("eyeTrackerSelection")
        eyeTrackerSelection.resize(804, 773)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(eyeTrackerSelection.sizePolicy().hasHeightForWidth())
        eyeTrackerSelection.setSizePolicy(sizePolicy)
        eyeTrackerSelection.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(eyeTrackerSelection)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.eyeTrackerSelection_2 = QtWidgets.QGridLayout()
        self.eyeTrackerSelection_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.eyeTrackerSelection_2.setObjectName("eyeTrackerSelection_2")
        self.EyelinkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.EyelinkBox.setChecked(True)
        self.EyelinkBox.setObjectName("EyelinkBox")
        self.eyeTrackerSelection_2.addWidget(self.EyelinkBox, 0, 0, 1, 1)
        self.TobiiBox = QtWidgets.QCheckBox(self.centralwidget)
        self.TobiiBox.setObjectName("TobiiBox")
        self.eyeTrackerSelection_2.addWidget(self.TobiiBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.eyeTrackerSelection_2, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textbox = QtWidgets.QTextEdit(self.centralwidget)
        self.textbox.setEnabled(False)
        self.textbox.setObjectName("textbox")
        self.gridLayout_2.addWidget(self.textbox, 1, 0, 1, 1)
        self.filebtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filebtn.sizePolicy().hasHeightForWidth())
        self.filebtn.setSizePolicy(sizePolicy)
        self.filebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.filebtn.setObjectName("filebtn")
        self.gridLayout_2.addWidget(self.filebtn, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 6, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.varKeyL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varKeyL.sizePolicy().hasHeightForWidth())
        self.varKeyL.setSizePolicy(sizePolicy)
        self.varKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.varKeyL.setObjectName("varKeyL")
        self.gridLayout.addWidget(self.varKeyL, 0, 2, 1, 1)
        self.varKey = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varKey.sizePolicy().hasHeightForWidth())
        self.varKey.setSizePolicy(sizePolicy)
        self.varKey.setMaximumSize(QtCore.QSize(100, 25))
        self.varKey.setObjectName("varKey")
        self.gridLayout.addWidget(self.varKey, 1, 2, 1, 1)
        self.Parsebtn = QtWidgets.QPushButton(self.centralwidget)
        self.Parsebtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Parsebtn.sizePolicy().hasHeightForWidth())
        self.Parsebtn.setSizePolicy(sizePolicy)
        self.Parsebtn.setMaximumSize(QtCore.QSize(100, 25))
        self.Parsebtn.setObjectName("Parsebtn")
        self.gridLayout.addWidget(self.Parsebtn, 1, 3, 1, 1)
        self.startKeyL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startKeyL.sizePolicy().hasHeightForWidth())
        self.startKeyL.setSizePolicy(sizePolicy)
        self.startKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.startKeyL.setObjectName("startKeyL")
        self.gridLayout.addWidget(self.startKeyL, 0, 0, 1, 1)
        self.startKey = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startKey.sizePolicy().hasHeightForWidth())
        self.startKey.setSizePolicy(sizePolicy)
        self.startKey.setMaximumSize(QtCore.QSize(100, 25))
        self.startKey.setObjectName("startKey")
        self.gridLayout.addWidget(self.startKey, 1, 0, 1, 1)
        self.stopKey = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopKey.sizePolicy().hasHeightForWidth())
        self.stopKey.setSizePolicy(sizePolicy)
        self.stopKey.setMaximumSize(QtCore.QSize(100, 25))
        self.stopKey.setObjectName("stopKey")
        self.gridLayout.addWidget(self.stopKey, 1, 1, 1, 1)
        self.stopKeyL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopKeyL.sizePolicy().hasHeightForWidth())
        self.stopKeyL.setSizePolicy(sizePolicy)
        self.stopKeyL.setMaximumSize(QtCore.QSize(100, 25))
        self.stopKeyL.setObjectName("stopKeyL")
        self.gridLayout.addWidget(self.stopKeyL, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.toggleSettings = QtWidgets.QCheckBox(self.centralwidget)
        self.toggleSettings.setObjectName("toggleSettings")
        self.gridLayout_4.addWidget(self.toggleSettings, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statusL = QtWidgets.QLabel(self.centralwidget)
        self.statusL.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusL.setFont(font)
        self.statusL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusL.setAlignment(QtCore.Qt.AlignCenter)
        self.statusL.setObjectName("statusL")
        self.verticalLayout_2.addWidget(self.statusL)
        self.bussyBar = QtWidgets.QProgressBar(self.centralwidget)
        self.bussyBar.setMaximum(1)
        self.bussyBar.setProperty("value", -1)
        self.bussyBar.setObjectName("bussyBar")
        self.verticalLayout_2.addWidget(self.bussyBar)
        self.progressBarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarL.sizePolicy().hasHeightForWidth())
        self.progressBarL.setSizePolicy(sizePolicy)
        self.progressBarL.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBarL.setFont(font)
        self.progressBarL.setScaledContents(False)
        self.progressBarL.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarL.setObjectName("progressBarL")
        self.verticalLayout_2.addWidget(self.progressBarL)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.cpuBarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuBarL.sizePolicy().hasHeightForWidth())
        self.cpuBarL.setSizePolicy(sizePolicy)
        self.cpuBarL.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cpuBarL.setFont(font)
        self.cpuBarL.setObjectName("cpuBarL")
        self.verticalLayout_2.addWidget(self.cpuBarL)
        self.cpuBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpuBar.sizePolicy().hasHeightForWidth())
        self.cpuBar.setSizePolicy(sizePolicy)
        self.cpuBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.cpuBar.setProperty("value", 24)
        self.cpuBar.setObjectName("cpuBar")
        self.verticalLayout_2.addWidget(self.cpuBar)
        self.memBarL = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBarL.sizePolicy().hasHeightForWidth())
        self.memBarL.setSizePolicy(sizePolicy)
        self.memBarL.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.memBarL.setFont(font)
        self.memBarL.setObjectName("memBarL")
        self.verticalLayout_2.addWidget(self.memBarL)
        self.memBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memBar.sizePolicy().hasHeightForWidth())
        self.memBar.setSizePolicy(sizePolicy)
        self.memBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.memBar.setProperty("value", 24)
        self.memBar.setObjectName("memBar")
        self.verticalLayout_2.addWidget(self.memBar)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 6, 0, 1, 3)
        self.optionsTab = QtWidgets.QTabWidget(self.centralwidget)
        self.optionsTab.setEnabled(True)
        self.optionsTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.optionsTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.optionsTab.setElideMode(QtCore.Qt.ElideLeft)
        self.optionsTab.setTabsClosable(False)
        self.optionsTab.setTabBarAutoHide(False)
        self.optionsTab.setObjectName("optionsTab")
        self.optionsTab1 = QtWidgets.QWidget()
        self.optionsTab1.setObjectName("optionsTab1")
        self.layoutWidget = QtWidgets.QWidget(self.optionsTab1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 209))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.screenResXL = QtWidgets.QLabel(self.layoutWidget)
        self.screenResXL.setObjectName("screenResXL")
        self.gridLayout_3.addWidget(self.screenResXL, 4, 0, 1, 1)
        self.screenW = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.screenW.setEnabled(False)
        self.screenW.setMaximum(10000.0)
        self.screenW.setSingleStep(0.5)
        self.screenW.setProperty("value", 52.5)
        self.screenW.setObjectName("screenW")
        self.gridLayout_3.addWidget(self.screenW, 3, 1, 1, 1)
        self.screenDistL = QtWidgets.QLabel(self.layoutWidget)
        self.screenDistL.setObjectName("screenDistL")
        self.gridLayout_3.addWidget(self.screenDistL, 2, 0, 1, 1)
        self.screenWL = QtWidgets.QLabel(self.layoutWidget)
        self.screenWL.setObjectName("screenWL")
        self.gridLayout_3.addWidget(self.screenWL, 3, 0, 1, 1)
        self.resolutionX = QtWidgets.QSpinBox(self.layoutWidget)
        self.resolutionX.setEnabled(False)
        self.resolutionX.setMaximum(100000)
        self.resolutionX.setProperty("value", 1920)
        self.resolutionX.setObjectName("resolutionX")
        self.gridLayout_3.addWidget(self.resolutionX, 4, 1, 1, 1)
        self.screenResYL = QtWidgets.QLabel(self.layoutWidget)
        self.screenResYL.setObjectName("screenResYL")
        self.gridLayout_3.addWidget(self.screenResYL, 5, 0, 1, 1)
        self.screenDist = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.screenDist.setEnabled(False)
        self.screenDist.setMaximum(1000.0)
        self.screenDist.setSingleStep(0.5)
        self.screenDist.setProperty("value", 75.0)
        self.screenDist.setObjectName("screenDist")
        self.gridLayout_3.addWidget(self.screenDist, 2, 1, 1, 1)
        self.resolutionY = QtWidgets.QSpinBox(self.layoutWidget)
        self.resolutionY.setEnabled(False)
        self.resolutionY.setMaximum(100000)
        self.resolutionY.setProperty("value", 1080)
        self.resolutionY.setObjectName("resolutionY")
        self.gridLayout_3.addWidget(self.resolutionY, 5, 1, 1, 1)
        self.paralellL = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paralellL.sizePolicy().hasHeightForWidth())
        self.paralellL.setSizePolicy(sizePolicy)
        self.paralellL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.paralellL.setObjectName("paralellL")
        self.gridLayout_3.addWidget(self.paralellL, 8, 0, 1, 1)
        self.nrCoresL = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrCoresL.sizePolicy().hasHeightForWidth())
        self.nrCoresL.setSizePolicy(sizePolicy)
        self.nrCoresL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.nrCoresL.setObjectName("nrCoresL")
        self.gridLayout_3.addWidget(self.nrCoresL, 9, 0, 1, 1)
        self.paralell = QtWidgets.QComboBox(self.layoutWidget)
        self.paralell.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paralell.sizePolicy().hasHeightForWidth())
        self.paralell.setSizePolicy(sizePolicy)
        self.paralell.setMaximumSize(QtCore.QSize(100, 25))
        self.paralell.setObjectName("paralell")
        self.gridLayout_3.addWidget(self.paralell, 8, 1, 1, 1)
        self.nrCores = QtWidgets.QTextEdit(self.layoutWidget)
        self.nrCores.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nrCores.sizePolicy().hasHeightForWidth())
        self.nrCores.setSizePolicy(sizePolicy)
        self.nrCores.setMaximumSize(QtCore.QSize(100, 25))
        self.nrCores.setObjectName("nrCores")
        self.gridLayout_3.addWidget(self.nrCores, 9, 1, 1, 1)
        self.sampFreqL = QtWidgets.QLabel(self.layoutWidget)
        self.sampFreqL.setObjectName("sampFreqL")
        self.gridLayout_3.addWidget(self.sampFreqL, 6, 0, 1, 1)
        self.sampleFreq = QtWidgets.QSpinBox(self.layoutWidget)
        self.sampleFreq.setMaximum(10000)
        self.sampleFreq.setProperty("value", 1000)
        self.sampleFreq.setObjectName("sampleFreq")
        self.gridLayout_3.addWidget(self.sampleFreq, 6, 1, 1, 1)
        self.pxPerDegL = QtWidgets.QLabel(self.layoutWidget)
        self.pxPerDegL.setObjectName("pxPerDegL")
        self.gridLayout_3.addWidget(self.pxPerDegL, 1, 0, 1, 1)
        self.pixMode = QtWidgets.QComboBox(self.layoutWidget)
        self.pixMode.setObjectName("pixMode")
        self.pixMode.addItem("")
        self.pixMode.addItem("")
        self.gridLayout_3.addWidget(self.pixMode, 1, 1, 1, 1)
        self.optionsTab.addTab(self.optionsTab1, "")
        self.saveOptionsTab = QtWidgets.QWidget()
        self.saveOptionsTab.setObjectName("saveOptionsTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.saveOptionsTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 12, 371, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.longbtn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.longbtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longbtn.sizePolicy().hasHeightForWidth())
        self.longbtn.setSizePolicy(sizePolicy)
        self.longbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.longbtn.setObjectName("longbtn")
        self.gridLayout_5.addWidget(self.longbtn, 8, 1, 1, 1)
        self.longL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longL.sizePolicy().hasHeightForWidth())
        self.longL.setSizePolicy(sizePolicy)
        self.longL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.longL.setObjectName("longL")
        self.gridLayout_5.addWidget(self.longL, 7, 1, 1, 1)
        self.duplicLongbtn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.duplicLongbtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicLongbtn.sizePolicy().hasHeightForWidth())
        self.duplicLongbtn.setSizePolicy(sizePolicy)
        self.duplicLongbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.duplicLongbtn.setObjectName("duplicLongbtn")
        self.gridLayout_5.addWidget(self.duplicLongbtn, 8, 2, 1, 1)
        self.fileTypeLongBtn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.fileTypeLongBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeLongBtn.sizePolicy().hasHeightForWidth())
        self.fileTypeLongBtn.setSizePolicy(sizePolicy)
        self.fileTypeLongBtn.setMaximumSize(QtCore.QSize(100, 25))
        self.fileTypeLongBtn.setObjectName("fileTypeLongBtn")
        self.fileTypeLongBtn.addItem("")
        self.fileTypeLongBtn.addItem("")
        self.fileTypeLongBtn.addItem("")
        self.fileTypeLongBtn.addItem("")
        self.fileTypeLongBtn.addItem("")
        self.gridLayout_5.addWidget(self.fileTypeLongBtn, 8, 3, 1, 1)
        self.RawFormatLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.RawFormatLabel.setFont(font)
        self.RawFormatLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.RawFormatLabel.setObjectName("RawFormatLabel")
        self.gridLayout_5.addWidget(self.RawFormatLabel, 3, 0, 1, 4)
        self.longName = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.longName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longName.sizePolicy().hasHeightForWidth())
        self.longName.setSizePolicy(sizePolicy)
        self.longName.setMaximumSize(QtCore.QSize(100, 25))
        self.longName.setObjectName("longName")
        self.gridLayout_5.addWidget(self.longName, 8, 0, 1, 1)
        self.DefaultDataLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DefaultDataLabel.setFont(font)
        self.DefaultDataLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.DefaultDataLabel.setObjectName("DefaultDataLabel")
        self.gridLayout_5.addWidget(self.DefaultDataLabel, 0, 0, 1, 4)
        self.parsedNameL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parsedNameL.sizePolicy().hasHeightForWidth())
        self.parsedNameL.setSizePolicy(sizePolicy)
        self.parsedNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.parsedNameL.setObjectName("parsedNameL")
        self.gridLayout_5.addWidget(self.parsedNameL, 1, 0, 1, 1)
        self.duplicLongL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duplicLongL.sizePolicy().hasHeightForWidth())
        self.duplicLongL.setSizePolicy(sizePolicy)
        self.duplicLongL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.duplicLongL.setObjectName("duplicLongL")
        self.gridLayout_5.addWidget(self.duplicLongL, 7, 2, 1, 1)
        self.rawName = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.rawName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawName.sizePolicy().hasHeightForWidth())
        self.rawName.setSizePolicy(sizePolicy)
        self.rawName.setMaximumSize(QtCore.QSize(100, 25))
        self.rawName.setObjectName("rawName")
        self.gridLayout_5.addWidget(self.rawName, 5, 0, 1, 1)
        self.rawNameL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawNameL.sizePolicy().hasHeightForWidth())
        self.rawNameL.setSizePolicy(sizePolicy)
        self.rawNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rawNameL.setObjectName("rawNameL")
        self.gridLayout_5.addWidget(self.rawNameL, 4, 0, 1, 1)
        self.parsedName = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.parsedName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parsedName.sizePolicy().hasHeightForWidth())
        self.parsedName.setSizePolicy(sizePolicy)
        self.parsedName.setMaximumSize(QtCore.QSize(100, 25))
        self.parsedName.setObjectName("parsedName")
        self.gridLayout_5.addWidget(self.parsedName, 2, 0, 1, 1)
        self.saveRawL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawL.sizePolicy().hasHeightForWidth())
        self.saveRawL.setSizePolicy(sizePolicy)
        self.saveRawL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.saveRawL.setObjectName("saveRawL")
        self.gridLayout_5.addWidget(self.saveRawL, 4, 1, 1, 1)
        self.fileTypeLongL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeLongL.sizePolicy().hasHeightForWidth())
        self.fileTypeLongL.setSizePolicy(sizePolicy)
        self.fileTypeLongL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fileTypeLongL.setObjectName("fileTypeLongL")
        self.gridLayout_5.addWidget(self.fileTypeLongL, 7, 3, 1, 1)
        self.saveRawbtn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.saveRawbtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawbtn.sizePolicy().hasHeightForWidth())
        self.saveRawbtn.setSizePolicy(sizePolicy)
        self.saveRawbtn.setMaximumSize(QtCore.QSize(100, 25))
        self.saveRawbtn.setObjectName("saveRawbtn")
        self.gridLayout_5.addWidget(self.saveRawbtn, 5, 1, 1, 1)
        self.longNameL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longNameL.sizePolicy().hasHeightForWidth())
        self.longNameL.setSizePolicy(sizePolicy)
        self.longNameL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.longNameL.setObjectName("longNameL")
        self.gridLayout_5.addWidget(self.longNameL, 7, 0, 1, 1)
        self.LongFormatLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LongFormatLabel.setFont(font)
        self.LongFormatLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.LongFormatLabel.setObjectName("LongFormatLabel")
        self.gridLayout_5.addWidget(self.LongFormatLabel, 6, 0, 1, 4)
        self.fileTypeL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeL.sizePolicy().hasHeightForWidth())
        self.fileTypeL.setSizePolicy(sizePolicy)
        self.fileTypeL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fileTypeL.setObjectName("fileTypeL")
        self.gridLayout_5.addWidget(self.fileTypeL, 1, 3, 1, 1)
        self.fileTypeBtn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.fileTypeBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeBtn.sizePolicy().hasHeightForWidth())
        self.fileTypeBtn.setSizePolicy(sizePolicy)
        self.fileTypeBtn.setMaximumSize(QtCore.QSize(100, 25))
        self.fileTypeBtn.setObjectName("fileTypeBtn")
        self.fileTypeBtn.addItem("")
        self.fileTypeBtn.addItem("")
        self.fileTypeBtn.addItem("")
        self.fileTypeBtn.addItem("")
        self.gridLayout_5.addWidget(self.fileTypeBtn, 2, 3, 1, 1)
        self.fileTypeRawL = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeRawL.sizePolicy().hasHeightForWidth())
        self.fileTypeRawL.setSizePolicy(sizePolicy)
        self.fileTypeRawL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fileTypeRawL.setObjectName("fileTypeRawL")
        self.gridLayout_5.addWidget(self.fileTypeRawL, 4, 3, 1, 1)
        self.fileTypeRawBtn = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.fileTypeRawBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTypeRawBtn.sizePolicy().hasHeightForWidth())
        self.fileTypeRawBtn.setSizePolicy(sizePolicy)
        self.fileTypeRawBtn.setMaximumSize(QtCore.QSize(100, 25))
        self.fileTypeRawBtn.setObjectName("fileTypeRawBtn")
        self.fileTypeRawBtn.addItem("")
        self.fileTypeRawBtn.addItem("")
        self.fileTypeRawBtn.addItem("")
        self.fileTypeRawBtn.addItem("")
        self.gridLayout_5.addWidget(self.fileTypeRawBtn, 5, 3, 1, 1)
        self.optionsTab.addTab(self.saveOptionsTab, "")
        self.gridLayout_4.addWidget(self.optionsTab, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 5, 1, 1, 1)
        eyeTrackerSelection.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(eyeTrackerSelection)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        eyeTrackerSelection.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(eyeTrackerSelection)
        self.statusbar.setObjectName("statusbar")
        eyeTrackerSelection.setStatusBar(self.statusbar)
        self.openFile = QtWidgets.QAction(eyeTrackerSelection)
        self.openFile.setObjectName("openFile")
        self.quitParser = QtWidgets.QAction(eyeTrackerSelection)
        self.quitParser.setShortcut("")
        self.quitParser.setObjectName("quitParser")
        self.unlockSettingsM = QtWidgets.QAction(eyeTrackerSelection)
        self.unlockSettingsM.setObjectName("unlockSettingsM")
        self.lockSettingsM = QtWidgets.QAction(eyeTrackerSelection)
        self.lockSettingsM.setEnabled(False)
        self.lockSettingsM.setObjectName("lockSettingsM")
        self.defSett = QtWidgets.QAction(eyeTrackerSelection)
        self.defSett.setObjectName("defSett")
        self.openDoc = QtWidgets.QAction(eyeTrackerSelection)
        self.openDoc.setObjectName("openDoc")
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.quitParser)
        self.menuSettings.addAction(self.defSett)
        self.menuSettings.addAction(self.openDoc)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(eyeTrackerSelection)
        self.optionsTab.setCurrentIndex(0)
        self.EyelinkBox.clicked['bool'].connect(self.TobiiBox.toggle)
        self.TobiiBox.clicked['bool'].connect(self.EyelinkBox.toggle)
        self.toggleSettings.toggled['bool'].connect(self.optionsTab.setVisible)
        QtCore.QMetaObject.connectSlotsByName(eyeTrackerSelection)

    def retranslateUi(self, eyeTrackerSelection):
        _translate = QtCore.QCoreApplication.translate
        eyeTrackerSelection.setWindowTitle(_translate("eyeTrackerSelection", "Eyetracker data parser"))
        self.EyelinkBox.setText(_translate("eyeTrackerSelection", "Eyelink 1000"))
        self.TobiiBox.setText(_translate("eyeTrackerSelection", "Tobii TX300"))
        self.filebtn.setText(_translate("eyeTrackerSelection", "Select file(s)"))
        self.varKeyL.setText(_translate("eyeTrackerSelection", "Variable prefix"))
        self.Parsebtn.setText(_translate("eyeTrackerSelection", "Parse"))
        self.startKeyL.setText(_translate("eyeTrackerSelection", "Start trial key"))
        self.stopKeyL.setText(_translate("eyeTrackerSelection", "Stop trial key"))
        self.toggleSettings.setText(_translate("eyeTrackerSelection", "Unlock settings"))
        self.statusL.setText(_translate("eyeTrackerSelection", "Parallel processing!"))
        self.progressBarL.setText(_translate("eyeTrackerSelection", "% of files Finished"))
        self.cpuBarL.setText(_translate("eyeTrackerSelection", "CPU usage"))
        self.memBarL.setText(_translate("eyeTrackerSelection", "Memory usage"))
        self.screenResXL.setText(_translate("eyeTrackerSelection", "Screen resolution X (px)"))
        self.screenDistL.setText(_translate("eyeTrackerSelection", "Distance from screen (cm)"))
        self.screenWL.setText(_translate("eyeTrackerSelection", "Screen width (cm)"))
        self.screenResYL.setText(_translate("eyeTrackerSelection", "Screen resolution Y (px)"))
        self.paralellL.setText(_translate("eyeTrackerSelection", "Parallel processing"))
        self.nrCoresL.setText(_translate("eyeTrackerSelection", "CPU cores"))
        self.sampFreqL.setText(_translate("eyeTrackerSelection", "Sample frequency (Hz)"))
        self.pxPerDegL.setText(_translate("eyeTrackerSelection", "Pixels per degree"))
        self.pixMode.setItemText(0, _translate("eyeTrackerSelection", "Automatic"))
        self.pixMode.setItemText(1, _translate("eyeTrackerSelection", "Manual"))
        self.optionsTab.setTabText(self.optionsTab.indexOf(self.optionsTab1), _translate("eyeTrackerSelection", "Options"))
        self.longL.setText(_translate("eyeTrackerSelection", "Save file"))
        self.fileTypeLongBtn.setItemText(0, _translate("eyeTrackerSelection", "CSV"))
        self.fileTypeLongBtn.setItemText(1, _translate("eyeTrackerSelection", "pickle"))
        self.fileTypeLongBtn.setItemText(2, _translate("eyeTrackerSelection", "HDF"))
        self.fileTypeLongBtn.setItemText(3, _translate("eyeTrackerSelection", "json"))
        self.fileTypeLongBtn.setItemText(4, _translate("eyeTrackerSelection", "MAT"))
        self.RawFormatLabel.setText(_translate("eyeTrackerSelection", "Raw data "))
        self.DefaultDataLabel.setText(_translate("eyeTrackerSelection", "Default data file "))
        self.parsedNameL.setText(_translate("eyeTrackerSelection", "Name extension"))
        self.duplicLongL.setText(_translate("eyeTrackerSelection", "Duplicate values"))
        self.rawNameL.setText(_translate("eyeTrackerSelection", "Name extension"))
        self.saveRawL.setText(_translate("eyeTrackerSelection", "Save file"))
        self.fileTypeLongL.setText(_translate("eyeTrackerSelection", "Save as"))
        self.longNameL.setText(_translate("eyeTrackerSelection", "Name extension"))
        self.LongFormatLabel.setText(_translate("eyeTrackerSelection", "Long format "))
        self.fileTypeL.setText(_translate("eyeTrackerSelection", "Save as"))
        self.fileTypeBtn.setItemText(0, _translate("eyeTrackerSelection", "pickle"))
        self.fileTypeBtn.setItemText(1, _translate("eyeTrackerSelection", "HDF"))
        self.fileTypeBtn.setItemText(2, _translate("eyeTrackerSelection", "json"))
        self.fileTypeBtn.setItemText(3, _translate("eyeTrackerSelection", "MAT"))
        self.fileTypeRawL.setText(_translate("eyeTrackerSelection", "Save as"))
        self.fileTypeRawBtn.setItemText(0, _translate("eyeTrackerSelection", "pickle"))
        self.fileTypeRawBtn.setItemText(1, _translate("eyeTrackerSelection", "HDF"))
        self.fileTypeRawBtn.setItemText(2, _translate("eyeTrackerSelection", "json"))
        self.fileTypeRawBtn.setItemText(3, _translate("eyeTrackerSelection", "MAT"))
        self.optionsTab.setTabText(self.optionsTab.indexOf(self.saveOptionsTab), _translate("eyeTrackerSelection", "Save options"))
        self.menuFile.setTitle(_translate("eyeTrackerSelection", "File"))
        self.menuSettings.setTitle(_translate("eyeTrackerSelection", "Settings"))
        self.openFile.setText(_translate("eyeTrackerSelection", "Select files(s)"))
        self.openFile.setStatusTip(_translate("eyeTrackerSelection", "Select file(s)"))
        self.quitParser.setText(_translate("eyeTrackerSelection", "Exit"))
        self.quitParser.setStatusTip(_translate("eyeTrackerSelection", "Exit parser"))
        self.unlockSettingsM.setText(_translate("eyeTrackerSelection", "Unlock settings"))
        self.unlockSettingsM.setStatusTip(_translate("eyeTrackerSelection", "Unlock settings"))
        self.lockSettingsM.setText(_translate("eyeTrackerSelection", "Lock settings"))
        self.lockSettingsM.setStatusTip(_translate("eyeTrackerSelection", "Lock settings"))
        self.defSett.setText(_translate("eyeTrackerSelection", "Load default settings"))
        self.defSett.setStatusTip(_translate("eyeTrackerSelection", "Load default setings"))
        self.openDoc.setText(_translate("eyeTrackerSelection", "Documentation"))
        self.openDoc.setStatusTip(_translate("eyeTrackerSelection", "Open documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    eyeTrackerSelection = QtWidgets.QMainWindow()
    ui = Ui_eyeTrackerSelection()
    ui.setupUi(eyeTrackerSelection)
    eyeTrackerSelection.show()
    sys.exit(app.exec_())

